### PR TITLE
docs: update FAQ.md w brew buildx info

### PR DESCRIPTION
**Pull request by gustafj**

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
Does the homebrew docker-buildx formula help with this? Seems easier...

```
rfay@rfay-tag1-m1:~/workspace/ddev$ brew info docker-buildx
==> docker-buildx: stable 0.10.5 (bottled), HEAD
Docker CLI plugin for extended build capabilities with BuildKit
https://docs.docker.com/buildx/working-with-buildx/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/docker-buildx.rb
License: Apache-2.0
==> Dependencies
Build: go ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
docker-buildx is a Docker plugin. For Docker to find this plugin, symlink it:
  mkdir -p ~/.docker/cli-plugins
  ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
==> Analytics
install: 7 (30 days), 62 (90 days), 4,709 (365 days)
install-on-request: 7 (30 days), 62 (90 days), 4,705 (365 days)
build-error: 0 (30 days)
```

**Comment by gustafj** [comment]
Yeah it does, which is the info I added to the readme. I left the old manual way intact as not everyone uses homebrew.

**Comment by rfay** [comment]
Sorry, I scanned it too fast. Thought I saw the nasty stuff from https://github.com/docker/buildx#windows-and-macos

**Comment by rfay** [comment]
Maybe time for a PR there too. Sorry for scanning so fast.

**Review by abiosoft — APPROVED** [review]
Thanks as usual.

**Pull request merged**
