### PR TITLE
docker: replace 127.0.0.1 with host gateway ip in docker daemon.json proxy settings

### LINKED ISSUE #1144: Colima does not auto-replace gateway address for proxy variables in docker daemon.json
### Description

When running behind a corporate proxy that runs on`127.0.0.1:9000`, colima automatically translates the proxy env vars to `192.168.5.2:9000`, but does not translate the proxy urls for `/etc/docker/daemon.json` 

### Version

colima version 0.7.5
git commit: 1588c066b9ab9dae8205ef265929c7eb43dca473

runtime: docker
arch: aarch64
client: v27.3.1
server: v27.1.1
limactl version 0.23.2
qemu-img version 9.1.0
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
> colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/c43990/.colima/default/docker.sock
```

### Reproduction Steps

1. Set http proxy variables to `http://127.0.0.1:9000`
2. `colima start --vm-type=vz --vz-rosetta=true`
3. `colima ssh -- env | grep -i` will reveal env vars have the translated proxy url (`http://192.165.5.2:9000`)
4. `colima ssh -- cat /etc/docker/daemon.json` to read daemon.json file

### Expected behaviour

Expected `/etc/docker/daemon.json`
```
{
  "exec-opts": [
    "native.cgroupdriver=cgroupfs"
  ],
  "features": {
    "buildkit": true
  },
  "proxies": {
    "http-proxy": "http://192.168.5.2:9000",
    "https-proxy": "http://192.168.5.2:9000",
    "no-proxy": "localhost,192.168.5.2"
  }
}
```

Actual `/etc/docker/daemon.json`

```
{
  "exec-opts": [
    "native.cgroupdriver=cgroupfs"
  ],
  "features": {
    "buildkit": true
  },
  "proxies": {
    "http-proxy": "http://127.0.0.1:9000",
    "https-proxy": "http://127.0.0.1:9000",
    "no-proxy": "REDACTED"
  }
  ```

### Additional context

The code that should do this resides here:
https://github.com/abiosoft/colima/blob/a58166e288acc54cc98d890fad49a643203b04e8/environment/container/docker/daemon.go#L34-L46

#1040  is an effective workaround, but it would be much more convenient and user friendly to set this automatically

### PR DESCRIPTION
**Pull request by rteeling-evernorth**
- Automatically replace 127.0.0.1 with host gateway ip in docker daemon.json proxy settings
- Refactored daemon.json to move fetching of gateway ip to a function for DRY

Fixes #1144

Related to #956, #1040

### CODE REVIEW

**Review by abiosoft — APPROVED** [review]

**Comment by abiosoft** [comment]
I am not sure what is preventing the github actions from successful running the virtual machines and starting Colima.

**Comment by rteeling-evernorth** [comment]
> I am not sure what is preventing the github actions from successfully running the virtual machines and starting Colima.

I've updated the failing jobs to verbose logging, hopefully that might reveal the issue

**Comment by rteeling-evernorth** [comment]
@abiosoft updated to very verbose - last ci run seems to have skipped integration, but i dont see anything on the workflow file that would cause that. do you need me do to anything specific on my end?

**Comment by abiosoft** [comment]
@rteeling-evernorth it has nothing to do with your contributions. It's just Github actions acting up.
I may merge this and troubleshoot that differently.

**Comment by abiosoft** [comment]
@rteeling-evernorth kindly remove the verbose flags and let's get this over the line.

Thanks :)

**Comment by rteeling-evernorth** [comment]
@abiosoft Done. Thanks for the speedy approval! Looking forward to bringing this to my org without having to explain how to handle the proxy stuff.

**Review by abiosoft — APPROVED** [review]

**Comment by rteeling-evernorth** [comment]
@abiosoft Thanks for moving so quickly on this. Do you have an idea of when this will be tagged/released to homebrew?

**Comment by abiosoft** [comment]
> @abiosoft Thanks for moving so quickly on this. Do you have an idea of when this will be tagged/released to homebrew?

You can already test it with `brew install --head colima`.

I would like to figure what's going on with Github actions and get that resolved before pushing a release. In the next few days hopefully.

**Comment by rteeling-evernorth** [comment]
Excellent! Thank you!

**Pull request merged**
